data:
  mat_dir: '/home/allent/Desktop/NII/data'
  visuals: 
    - orig_cache # original files, each channel plotted
  img_scale: [1,1,1,1,1] #scales each channel FOR VISUALS - given by Mihoko
  normalize: True
  
  batch_size: 1
  ## define the disease and control as the folders where the data is located
  control: 'Cont'
  disease: 'PAN'
  resample: [512,512]

# feature_extraction:
#   method: Pyradiomics
#   features:
#     - ALL
#   voxel_based: True
#   x_bound: 200
#   y_bound: 200
#   plot: True
#   compare: ['run_PCA', 'histogram_per_img']

# feature_extraction:
#   method: Pyfeats
#   features:
#     - ALL
#   plot: True
#   compare: ['plot_stat_difference']

# feature_extraction:
#   method: SkIMG
#   features:
#     - HOG
#   orientations: 9
#   pixels_per_cell: 8 #assumes cubic shape
#   cells_per_block: 4 #assumes cubic shape
#   hog_intensity_rescale: 1 #0.1 #for visuals, rescale

#   plot: True
#   compare:  ['run_PCA', 'histogram_per_img']


feature_extraction:
  method: SkIMG
  features:
    - CANNY
  sigma: 5

  plot: True
  compare:  ['run_PCA', 'histogram_per_img']


output:
  loc: ./output
  visuals:
    - plot_features